apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-microservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: document
  template:
    metadata:
      labels:
        app: document
    spec:
      containers:
        - name: document-container
          image: dwaiproduction/erp:document
      imagePullSecrets:
        - name: regcredv2
      envFrom:
        - configMapRef:
            name: document-config
---
apiVersion: v1
kind: Service
metadata:
  name: document-microservice-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: document
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30006