apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-microservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registration
  template:
    metadata:
      labels:
        app: registration
    spec:
      containers:
        - name: registration-container
          image: registration:0.1.0
      envFrom:
        - configMapRef:
            name: registration-config
---
apiVersion: v1
kind: Service
metadata:
  name: registration-microservice-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: registration
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007