kind: Service
apiVersion: v1
metadata:
  name: postgres-published
spec:
  ports:
    - name: http
      port: 5432
      targetPort: 5432
      nodePort: 30000
      protocol: TCP
  selector:
    app: mypostgres
  type: LoadBalancer
